@host = http://localhost:3000

@baseUrl = {{host}}/api/v1

@contentType = application/json

###
GET {{host}}
Content-Type: {{contentType}}

###

GET {{host}}/healthcheck
Content-Type: {{contentType}}

###

POST {{baseUrl}}/todos
Content-Type: {{contentType}}

{
    "task": "task to do",
    "description": "description",
    "dueDate": "12/08/2024"
}

###

GET {{baseUrl}}/todos
Content-Type: {{contentType}}


###

GET {{baseUrl}}/todos/86f4a464-3f26-46af-a9f5-f8a2ccbbb832
Content-Type: {{contentType}}

###

PATCH {{baseUrl}}/todos/86f4a464-3f26-46af-a9f5-f8a2ccbbb832
Content-Type: {{contentType}}

{
   
    "task": "task NOT TO do",
    "description": "description",
    "dueDate": "12/08/2024",
    "isDone": "true"
}

###
DELETE {{baseUrl}}/todos/86f4a464-3f26-46af-a9f5-f8a2ccbbb832
Content-Type: {{contentType}}

